name: release
on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "public/**"
      - "tsconfig.json"
      - "webpack.config.js"
      - "package*.json"
      - ".github/workflows/release.yaml"
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: ["20"]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Package
        run: zip -r instagram-pic-enlarger.zip ./release/*
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Instagram Pic Enlarger
          body: Download latest version
          tag_name: v1.0.0
          files: instagram-pic-enlarger.zip
          make_latest: true
