name: test
on:
  push:
    branches:
      - master
    paths:
      - "**"
      - "!README.md"
      - "!.gitignore"
      - "!.github/**"
      - ".github/workflows/test.yaml"
  pull_request:
    branches:
      - master
    paths:
      - "**"
      - "!README.md"
      - "!.gitignore"
      - "!.github/**"
      - ".github/workflows/test.yaml"
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["20"]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Setup tests
        run: npm run test-setup
      - name: Run tests
        run: npm run test
